spring.application.name=backend
spring.data.redis.host=redis
spring.data.redis.port=6379

spring.profiles.include=email

# jpa show sql query
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true




