# ??? CORS ??
cors.allowed-origins=http://travelshoot.store,https://travelshoot.store

# ????? ?????
kakao.pay.redirect-base-url=http://travelshoot.store

# ?? ??
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.domain=.travelshoot.store