spring.application.name=backend
spring.data.redis.host=redis
spring.data.redis.port=6379

spring.profiles.include=email

# Gmail email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noreply.memoryforest@gmail.com
spring.mail.password=icza lfno ymmt ntov
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
